### PR TITLE
Migrate to Typescript

### PR DESCRIPTION
**Pull request by Abbondanzo**
Working on producing an accurate definition file before breaking apart the index file into several functions. Made this PR to track progress but also might need help from @dschonholtz and @DarkAce65 to complete the work. The `three-gltf-loader` is not stable and could prove to be a pain.

Progress trackers:
- [x] Migrate `ar.js` library to typescript definition file
- [x] Enforce `noImplicitAny` requirement
- [x] Declare `three-gltf-loader` module support
- [x] Export model-loading functionality into separate async/await promise function

### CODE REVIEW

**Comment by Abbondanzo** [comment]
With this most recent commit, update messages are successfully propagated down to the scenes and they are updating correctly. Rendering happens as expected. The only errors that occur are from the missing files assigned to the sky scenes. 

That said, the trolley problem is still commented out, as well as portal animations. I want to revisit the stability of our marker tracking before continuing. If so much as one small corner of the tracker falls out of frame, the animation unloads.

**Review by dschonholtz — APPROVED** [review]
This is so incredible. Thanks for taking my hacks and making it a respectable code base.
I love it.

**Comment by Abbondanzo** [comment]
^ With that last commit, I moved the dependency to the `lib` folder with an explicit declaration file. In the future, we can pull in three.js GLTF loader versions from [here](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/GLTFLoader.js) without having to rely on some third-party person to copy + paste for us. This also guarantees that whenever we update three, we can match the example loader version against that.

**Comment by dschonholtz** [comment]
I'm going to go ahead and merge this because I want to move the rest of the work I've done into here in prep for the meeting tonight.
Plus there is some other stuff I want to do without worries of merge conflicts.

**Pull request merged**
